// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiDnWArbJTAoWBGhs9jGYwwJLfVn8qJEs',
    appId: '1:237453178155:web:6ba9bc0df9837aac75416e',
    messagingSenderId: '237453178155',
    projectId: 'mobile-spotify-clone',
    authDomain: 'mobile-spotify-clone.firebaseapp.com',
    storageBucket: 'mobile-spotify-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADrhLNryTuZH931c3plXnL65PIZ-LWtaE',
    appId: '1:237453178155:android:bb08f0800448217f75416e',
    messagingSenderId: '237453178155',
    projectId: 'mobile-spotify-clone',
    storageBucket: 'mobile-spotify-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-7DG1zyEXM-9ILHuGvzmaVzoHk1J-oU',
    appId: '1:237453178155:ios:4c68990f2a2eb22875416e',
    messagingSenderId: '237453178155',
    projectId: 'mobile-spotify-clone',
    storageBucket: 'mobile-spotify-clone.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-7DG1zyEXM-9ILHuGvzmaVzoHk1J-oU',
    appId: '1:237453178155:ios:4c68990f2a2eb22875416e',
    messagingSenderId: '237453178155',
    projectId: 'mobile-spotify-clone',
    storageBucket: 'mobile-spotify-clone.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiDnWArbJTAoWBGhs9jGYwwJLfVn8qJEs',
    appId: '1:237453178155:web:821c9de191e52e6575416e',
    messagingSenderId: '237453178155',
    projectId: 'mobile-spotify-clone',
    authDomain: 'mobile-spotify-clone.firebaseapp.com',
    storageBucket: 'mobile-spotify-clone.appspot.com',
  );
}
